Name: pointSync
Host: 0.0.0.0
Port: 8888

Mysql:
  database: point
  password: rootpasswd
  port: 3306
  max_open_conns: 1500
  host: 127.0.0.1
  max_conn_max_lifetime: 300
  user: root
  max_idle_conns: 10
Kv:
  Redis:
    - pass: 
      host: 127.0.0.1:6379
      type: node

AppLog:
  Mode: file
  Path: ./logs                    # 日志文件存放目录
  Compress: true                  # 是否压缩旧日志文件
  KeepDays: 7
  Level: info
  ServiceName: pointSync-service
KqPusherConf:
  Brokers:
    - 127.0.0.1:9092
  Topic: point-topic
  Partitions: 1  # 分区数
  ReplicationFactor: 1  # 副本数
  RetentionMs: 604800000  # 消息保留时间，单位毫秒
  UserMaxCount: 1  # 每个用户最大积分数量
  UserLimit: 1  # 每个用户每次推送积分数量
KqConsumerConf:
  Name: kqConsumer
  Brokers:
    - 127.0.0.1:9092
  Group: kqConsumer
  Topic: point-topic
  Offset: first
  Consumers: 1
  Processors: 1    

AnkrCfg:
  apiKey: 875925cffe4dc81b18b7a8a2ea558ef3cd0eee2be63a27145f8c4d69cbb6a22b
  httpsURL: https://rpc.ankr.com/eth_sepolia/
